platform :ios, "12.0"

use_frameworks!
inhibit_all_warnings!


source 'https://github.com/CocoaPods/Specs.git'


def major_pods
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'Firebase/Core'
end

target '___PROJECTNAME___' do

	major_pods

end

target '___PROJECTNAME___Tests' do

	major_pods

end

target '___PROJECTNAME___UITests' do

	major_pods

end
